api/urls.py
from django.urls import path

from .views import api_detail_customer_view, api_delete_customer_view, api_create_customer_view, \
    api_update_customer_view, api_accounts_login_view, ApiCustomerListView, ApiOrderListView, ApiOrderDetailListView, \
    api_create_order_view, api_delete_order_view, api_create_order_product_view, ApiProductListView

app_name = 'api'

urlpatterns = [
    path('accounts/login', api_accounts_login_view, name='account-login'),

    path('customers', ApiCustomerListView.as_view(), name='customers'),
    path('customer/create', api_create_customer_view, name='customer-create'),
    path('customer/<int:pk>/', api_detail_customer_view, name='customer-detail'),
    path('customer/<int:pk>/update', api_update_customer_view, name='customer-update'),
    path('customer/<int:pk>/delete', api_delete_customer_view, name='customer-delete'),

    path('products', ApiProductListView.as_view(), name='products'),

    path('orders', ApiOrderListView.as_view(), name='orders'),
    path('order/create', api_create_order_view, name='order-create'),
    path('order/<int:pk>/', ApiOrderDetailListView.as_view(), name='order-detail'),
    path('order/<int:pk>/delete', api_delete_order_view, name='order-delete'),

    path('order/<int:pk>/order-product/<int:opk>/create', api_create_order_product_view, name='order-product-create'),
]

core/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, include
from . import views
from .views import ProductView, ProductDetailView, CustomerView, OrderView, OrderDetailView, ProductCreate, \
    ProductUpdate, ProductDelete, CustomerCreate, CustomerDetailView, CustomerUpdate, CustomerDelete, OrderCreate, \
    OrderProductDelete, OrderProductCreate, OrderDelete, OrderProductUpdate, OverviewView

app_name = 'core'

urlpatterns = [
    path('api/', include('api.urls', 'api')),

    path('', ProductView.as_view(), name='index'),
    path('overview/', OverviewView.as_view(), name='overview'),


    path('products/', ProductView.as_view(), name='products'),
    path('product/create/', ProductCreate.as_view(), name='product-create'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', ProductUpdate.as_view(), name='product-update'),
    path('product/<int:pk>/delete', ProductDelete.as_view(), name='product-delete'),

    path('customers/', CustomerView.as_view(), name='customers'),
    path('customer/create/', CustomerCreate.as_view(), name='customer-create'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/<int:pk>/update', CustomerUpdate.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete', CustomerDelete.as_view(), name='customer-delete'),

    path('orders/', OrderView.as_view(), name='orders'),
    path('order/create/', OrderCreate.as_view(), name='order-create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order/<int:pk>/delete', OrderDelete.as_view(), name='order-delete'),

    path('order/<int:pk>/order-product/create', OrderProductCreate.as_view(), name='order-product-create'),
    path('order/<int:pk>/order-product/<int:opk>/update', OrderProductUpdate.as_view(), name='order-product-update'),
    path('order/<int:pk>/order-product/<int:opk>/delete', OrderProductDelete.as_view(), name='order-product-delete'),

]

edenpharma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

core/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    street = models.CharField(max_length=128, blank=True)
    city = models.CharField(max_length=128, blank=True)
    zip = models.CharField(max_length=128, blank=True)
    phone_number = models.CharField(max_length=15, blank=True)
    created_at = models.DateTimeField(editable=False, null=True)
    updated_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Customer, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('core:customer', kwargs={'pk': self.id})


class Product(models.Model):
    title = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    created_at = models.DateTimeField(editable=False, null=True)
    updated_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(Product, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('core:product', kwargs={'pk': self.id})


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(editable=False, null=True)

    def save(self, *args, **kwargs):
        # https://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add/1737078#1737078
        if not self.id:
            self.created_at = timezone.now()
        return super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return f'Objednavka #{self.id} pre {self.customer.name}'


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, default=None)
    quantity = models.IntegerField(default=0)
    created_at = models.DateTimeField(editable=False, null=True)
    updated_at = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super(OrderProduct, self).save(*args, **kwargs)

core/forms.py
from django import forms
from . import models


class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['title']

core/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils import timezone

from core.models import Product, Customer, Order, OrderProduct


def is_user_admin(self):
    return self.request.user.groups.filter(name='admin').exists()


@login_required
def index(request):
    return render(request, 'core/index.html')


class CustomerRow:
    def __init__(self, customer_name, products):
        self.customer_name = customer_name
        self.products = products


class OverviewView(LoginRequiredMixin, TemplateView):
    context_object_name = 'context'
    template_name = 'core/overview.html'

    def get_context_data(self, **kwargs):
        context = super(OverviewView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.all()

        num_of_customers = len(Customer.objects.all())
        num_of_products = len(Product.objects.all())
        context['customers'] = [None] * num_of_customers

        for i, customer in enumerate(Customer.objects.all()):
            context['customers'][i] = CustomerRow(customer.name, [0] * num_of_products)
            for j, product in enumerate(Product.objects.all()):
                for order in Order.objects.filter(customer_id=customer.id):
                    for order_product in OrderProduct.objects.filter(order_id=order.id, product_id=product.id):
                        context['customers'][i].products[j] += order_product.quantity

        for customer in context['customers']:
            print(customer)
            print(customer.customer_name)
            print(customer.products)

        return context


class ProductView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'core/products.html'


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'core/product.html'


class ProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Product
    fields = ['title', 'price']
    success_url = reverse_lazy('core:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = True
        return context

    def test_func(self):
        if is_user_admin(self):
            return True
        return False


class ProductUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    fields = ['title', 'price']

    def get_success_url(self):
        return reverse('core:product-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = False
        return context

    def test_func(self):
        if is_user_admin(self):
            return True
        return False


class ProductDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('core:products')

    def test_func(self):
        if is_user_admin(self):
            return True
        return False


class CustomerView(LoginRequiredMixin, ListView):
    model = Customer
    template_name = 'core/customers.html'


class CustomerDetailView(LoginRequiredMixin, DetailView):
    model = Customer
    template_name = 'core/customer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_auth_user_owner'] = self.get_object().user.id == self.request.user.id
        context['orders'] = Order.objects.filter(customer_id=self.kwargs['pk'])
        return context


class CustomerCreate(LoginRequiredMixin, CreateView):
    model = Customer
    fields = ['name', 'city', 'street', 'zip', 'phone_number']
    success_url = reverse_lazy('core:customers')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = True
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CustomerCreate, self).form_valid(form)


class CustomerUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Customer
    fields = ['name', 'city', 'street', 'zip', 'phone_number']

    def get_success_url(self):
        return reverse('core:customer-detail', kwargs={'pk': self.object.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_create'] = False
        return context

    def test_func(self):
        if is_user_admin(self):
            return True
        return self.get_object().user.id == self.request.user.id


class CustomerDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('core:customers')

    def test_func(self):
        if is_user_admin(self):
            return True
        return self.get_object().user.id == self.request.user.id


# ============================
class OrderView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'core/orders.html'

    def get_queryset(self):
        if is_user_admin(self):
            return Order.objects.all()
        return Order.objects.filter(user_id=self.request.user.id)


class OrderCreate(LoginRequiredMixin, CreateView):
    model = Order
    fields = ['customer']

    def get_form(self, *args, **kwargs):
        form = super(OrderCreate, self).get_form(*args, **kwargs)
        form.fields['customer'].queryset = Customer.objects.all()
        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(OrderCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse('core:order-detail', kwargs={'pk': self.object.id})


class OrderDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Order
    template_name = 'core/order.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        created_at = Order.objects.get(id=self.kwargs['pk']).created_at
        if created_at is not None:
            context['created_at_formatted'] = timezone.localtime(created_at).strftime("%d.%m.%Y %H:%M")
        else:
            context['created_at_formatted'] = None
        context['order_product_list'] = OrderProduct.objects.filter(order_id=self.get_object().id)
        return context

    def test_func(self):
        if is_user_admin(self):
            return True
        return self.get_object().user.id == self.request.user.id


class OrderDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Order
    success_url = reverse_lazy('core:orders')

    def test_func(self):
        if is_user_admin(self):
            return True
        return self.get_object().user.id == self.request.user.id


class OrderProductCreate(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = OrderProduct
    fields = ['product', 'quantity']

    def form_valid(self, form):
        form.instance.order = Order.objects.get(id=self.kwargs['pk'])
        return super(OrderProductCreate, self).form_valid(form)

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('core:order-detail', kwargs={'pk': pk})

    def test_func(self):
        if is_user_admin(self):
            return True
        return Order.objects.get(id=self.kwargs['pk']).user.id == self.request.user.id


class OrderProductUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = OrderProduct
    fields = ['product', 'quantity']

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('core:order-detail', kwargs={'pk': pk})

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        order_id = self.kwargs['pk']
        order_product_id = self.kwargs['opk']

        order = Order.objects.get(id=order_id)
        queryset = OrderProduct.objects.get(order_id=order_id, id=order_product_id)

        if not queryset or not order:
            raise Http404

        return queryset

    def test_func(self):
        if is_user_admin(self):
            return True
        return Order.objects.get(id=self.kwargs['pk']).user.id == self.request.user.id


class OrderProductDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = OrderProduct

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        order_id = self.kwargs['pk']
        order_product_id = self.kwargs['opk']

        order = Order.objects.get(id=order_id)
        queryset = OrderProduct.objects.get(order_id=order_id, id=order_product_id)

        if not queryset or not order:
            raise Http404

        context = {
            'order': order,
            'product': queryset
        }

        return context

    def delete(self, request, *args, **kwargs):
        order_id = self.kwargs['pk']
        order_product_id = self.kwargs['opk']

        order_product = OrderProduct.objects.filter(order_id=order_id, id=order_product_id)
        order_product.delete()

        return HttpResponseRedirect(reverse('core:order-detail', kwargs={'pk': order_id}))

    def test_func(self):
        if is_user_admin(self):
            return True
        return Order.objects.get(id=self.kwargs['pk']).user.id == self.request.user.id

core/templates/core/customer.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
    <br>
    <h1>{{ object.name }}</h1>
    <br>

    {% if is_auth_user_owner or request.user|has_group:"admin" %}
        <a href="{% url "core:customer-update" object.id %}">Edit</a>
        &nbsp;&nbsp;&nbsp;
        <a href="{% url "core:customer-delete" object.id %}">Delete</a>
    {% endif %}

    <br><br>
    <h4>Adresa</h4>
    <p>Ulica: <b>{{ object.street }}</b></p>
    <p>Mesto: <b>{{ object.city }}</b></p>
    <p>PSČ:   <b>{{ object.zip }}</b></p>
    <h4>Kontakt</h4>
    <p>Telefón: <b>{{ object.phone_number }}</b></p>
    <h4>Objednávky</h4>
    <br>
    <table class="table table-bordered">
    <thead class="thead-light">
    <tr>
        <th>Objednavka</th>
    </tr>
    </thead>
    {% for order in orders %}
        <tr>
            <td><a href="{% url 'core:order-detail' order.id %}">{{ order }}</a></td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

core/templates/core/customer_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>Odstránenie zákazníka</h1>
    <br>
    <form method="post">{% csrf_token %}
        Odstrániť zákazníka <b>{{ object }}</b>?<br>
        Budú odstránené všetky zákazníkove objednávky. <br><br>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

core/templates/core/customer_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    {% if is_create %}
        <h1>Vytvoriť nového zákazníka</h1>
    {% else %}
        <h1>Upraviť zákazníka</h1>
    {% endif %}
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

core/templates/core/customers.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>Zákazníci</h1>
    <br>
    <a href="{% url 'core:customer-create' %}">Nový zákazník</a>
    <br><br>
    <table class="table table-bordered">

        <tr>
            <th class="table-success">Zákazník</th>
            <th class="table-success" style="white-space: nowrap; width:1%;">Vytvorený používateľom</th>
        </tr>

        {% for customer in object_list %}
            <tr>
                <td><a href="{% url 'core:customer-detail' customer.id %}">{{ customer }}</a></td>
                <td>{{ customer.user }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

core/templates/core/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>This is index</h1>
{% endblock %}

core/templates/core/order.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>{{ object }}</h1>
    <br>
    <a href="{% url "core:order-product-create" object.id %}">Pridať produkt</a>
    &nbsp;&nbsp;&nbsp;
    <a href="{% url "core:order-delete" object.id %}">Zmazať objednávku</a>
    <br><br>
    <p>Objednávku vytvoril <b>{{ object.user }}</b></p>
    <p>Dátum vytvorenia <b>{{ created_at_formatted }}</b></p>
    <table class="table table-bordered">
        <thead class="thead-light">
            <tr>
                <th>Produkt</th>
                <th>Kvantita</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        {% for order_product in order_product_list %}
            <tr>
                <td>{{ order_product }}</td>
                <td>{{ order_product.quantity }}</td>
                <td><a href="{% url "core:order-product-update" pk=order_product.order.id opk=order_product.id %}">edit</a></td>
                <td><a href="{% url "core:order-product-delete" pk=order_product.order.id opk=order_product.id %}">delete</a></td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

core/templates/core/order_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>Odstránenie objednávky</h1>
    <br>
    <form method="post">{% csrf_token %}
        Odstrániť objednávku <b>{{ object }}</b>?
        <br><br>
        <input type="submit" value="Delete"/>
    </form>
{% endblock %}

core/templates/core/order_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <h1>Vytvoriť novú objednávku</h1>
    <br>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

core/templates/core/orderproduct_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <br>
    <h1>Odstránenie produktu z objednávky</h1>
    <br>
    <form method="post">{% csrf_token %}
        Odstrániť produkt <b>{{ object.product }}</b> z objednávky <b>{{ object.order }}</b>?
        <br><br>
        <input type="submit" value="Delete"/>
    </form>
{% endblock %}

core/templates/core/orderproduct_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Pridat produkt do objednavky</h1>
    <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

core/templates/core/orders.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
    <br>
    {% if request.user|has_group:"admin" %}
        <h1>Všetky objednávky</h1>
    {% else %}
        <h1>Moje objednávky</h1>
    {% endif %}
    <br>
    <a href="{% url 'core:order-create' %}">Nová objednávka</a>
    <br><br>
    <table class="table table-bordered">
        <thead class="thead-light">
        <tr>
            <th>Objednávka</th>
        </tr>
        </thead>
        {% for order in object_list %}
            <tr>
                <td><a href="{% url 'core:order-detail' order.id %}">{{ order }}</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

core/templates/core/overview.html
{% extends 'base.html' %}

{% block content %}
    <br>
        <h1>Prehľad</h1>
    <br>
    <table class="table table-sm table-bordered" style="display: block !important; overflow-x: auto!important; white-space: nowrap!important;">

        <tr>
            <td class="table-secondary"></td>
            {% for product in products %}
                <th style="word-wrap: break-word;min-width: 140px;max-width: 140px; white-space: normal !important;" class="table-primary">
                        {{ product }}
                </th>
            {% endfor %}
        </tr>

        {% for customer in customers %}
            <tr>

                <th class="table-success">{{ customer.customer_name }}</th>
                {% for product in customer.products %}

                    <th class="table-default">{{ product }}</th>

                {% endfor %}

            </tr>
        {% endfor %}
    </table>







{% endblock %}

core/templates/core/product_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    {% if is_create %}
        <h1>Vytvoriť nový produkt</h1>
    {% else %}
        <h1>Upraviť produkt</h1>
    {% endif %}
    <br>
    <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input type="submit" value="Submit">
</form>
{% endblock %}

core/templates/core/products.html
{% extends 'base.html' %}
{% load auth_extras %}
{% block content %}
    <br>
    <h1>Produkty</h1>
    <br>

    {% if request.user|has_group:"admin" %}
        <a href="{% url 'core:product-create' %}">Nový produkt</a>
        <br><br>
    {% endif %}

    <table class="table table-bordered">
        <tr>
            <th class="table-primary">Produkt</th>
            <th class="table-primary">Cena</th>
        </tr>

        {% for product in object_list %}
            <tr>
                <td><a href="{% url 'core:product-detail' product.id %}">{{ product }}</a></td>
                <td>{{ product.price }}€</td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}