accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

api/urls.py
from django.urls import path

from .views import api_detail_customer_view, api_delete_customer_view, api_create_customer_view, \
    api_update_customer_view, api_accounts_login_view, ApiCustomerListView, ApiOrderListView, ApiOrderDetailListView, \
    api_create_order_view, api_delete_order_view, api_create_order_product_view, ApiProductListView

app_name = 'api'

urlpatterns = [
    path('accounts/login', api_accounts_login_view, name='account-login'),

    path('customers', ApiCustomerListView.as_view(), name='customers'),
    path('customer/create', api_create_customer_view, name='customer-create'),
    path('customer/<int:pk>/', api_detail_customer_view, name='customer-detail'),
    path('customer/<int:pk>/update', api_update_customer_view, name='customer-update'),
    path('customer/<int:pk>/delete', api_delete_customer_view, name='customer-delete'),

    path('products', ApiProductListView.as_view(), name='products'),

    path('orders', ApiOrderListView.as_view(), name='orders'),
    path('order/create', api_create_order_view, name='order-create'),
    path('order/<int:pk>/', ApiOrderDetailListView.as_view(), name='order-detail'),
    path('order/<int:pk>/delete', api_delete_order_view, name='order-delete'),

    path('order/<int:pk>/order-product/<int:opk>/create', api_create_order_product_view, name='order-product-create'),
]

core/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path, include
from . import views
from .views import ProductView, ProductDetailView, CustomerView, OrderView, OrderDetailView, ProductCreate, \
    ProductUpdate, ProductDelete, CustomerCreate, CustomerDetailView, CustomerUpdate, CustomerDelete, OrderCreate, \
    OrderProductDelete, OrderProductCreate, OrderDelete, OrderProductUpdate, OverviewView

app_name = 'core'

urlpatterns = [
    path('api/', include('api.urls', 'api')),

    path('', ProductView.as_view(), name='index'),
    path('overview/', OverviewView.as_view(), name='overview'),


    path('products/', ProductView.as_view(), name='products'),
    path('product/create/', ProductCreate.as_view(), name='product-create'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:pk>/update', ProductUpdate.as_view(), name='product-update'),
    path('product/<int:pk>/delete', ProductDelete.as_view(), name='product-delete'),

    path('customers/', CustomerView.as_view(), name='customers'),
    path('customer/create/', CustomerCreate.as_view(), name='customer-create'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('customer/<int:pk>/update', CustomerUpdate.as_view(), name='customer-update'),
    path('customer/<int:pk>/delete', CustomerDelete.as_view(), name='customer-delete'),

    path('orders/', OrderView.as_view(), name='orders'),
    path('order/create/', OrderCreate.as_view(), name='order-create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order/<int:pk>/delete', OrderDelete.as_view(), name='order-delete'),

    path('order/<int:pk>/order-product/create', OrderProductCreate.as_view(), name='order-product-create'),
    path('order/<int:pk>/order-product/<int:opk>/update', OrderProductUpdate.as_view(), name='order-product-update'),
    path('order/<int:pk>/order-product/<int:opk>/delete', OrderProductDelete.as_view(), name='order-product-delete'),

]

edenpharma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

templates/base.html
{% load static %}
{% load auth_extras %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edenpharma</title>
    <link rel="icon" href="{% static 'img/eden-pharma-favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>


<nav class="navbar navbar-expand-sm bg-light">
    <div class="container">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:products' %}">Produkty</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:customers' %}">Zákazníci</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:orders' %}">Objednávky</a>
            </li>
            {% if request.user|has_group:"admin" %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:overview' %}">Prehľad</a>
                </li>
            {% endif %}
        </ul>
        <div class="mx-auto order-0">
            <img src="{% static 'img/eden-pharma-logo.png' %}" alt="logo" style="width: 140px;">
        </div>
        {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item nav-link">
                    Ste prihlásený ako <b>{{ user }}</b>
                </li>
                <li class="nav-item">
                    <form id="logout-form" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <a class="nav-link" href="#" onclick="document.getElementById('logout-form').submit()">Odhlásiť
                            sa</a>
                    </form>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>